### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by SinghiDivyanshu** [habrman/FaceRecognition#13]
I'm getting around 5 to 6 FPS. How to increase FPS.

**Comment by habrman** [comment]
I haven't spent any time optimizing the pipeline and there are some things that you can't to anything about so you need to change the networks or the approach. You can read my answer here to find a couple of approaches to make it faster: https://github.com/habrman/FaceRecognition/issues/6#issuecomment-392350371. If you only want to run it as fast as possible on all the frames in a video you could also run the frames in batches instead of one frame at a time.
