### ISSUE TITLE
No module name CV2

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [habrman/FaceRecognition#14]
My program is giving error no module found naming cv2 in line 5

**Comment by alex-o98** [comment]
You don't have CV2 installed. Install CV2 then see if it's working. To do this on linux use pip3 install opencv-python, or pip install opencv-python (If for Python2).

On windows open cmd, copy the path to the pip (If it isn't already in PATH, otherwise just type pip), then type  install opencv-pyrhon

**Comment by PrakharPrashantSingh** [comment]
> You don't have CV2 installed. Install CV2 then see if it's working. To do this on linux use pip3 install opencv-python, or pip install opencv-python (If for Python2).
> 
> On windows open cmd, copy the path to the pip (If it isn't already in PATH, otherwise just type pip), then type install opencv-pyrhon

Thanks! It worked. I was missing -Python after OpenCv
