### ISSUE TITLE
How do add new person image in model runtime.

### ISSUE THREAD

**Issue by Iamsiraj** [habrman/FaceRecognition#19]
Ok so here is the scenario:
1. My model detects unknown person image, and captures it face, generate an unique id and save it in ids folder.
2. My model again detects that face and returns it ID all in run time. 

Right now, when I start the model it gets all the images and train itself, but I do not wana start my model everytime I add new image. Is there any way I can do this in real time ?

**Comment by habrman** [comment]
Yes you can do this and it's not that difficult. You could e.g. add a button [here](https://github.com/habrman/FaceRecognition/blob/3b729f73a35ad68b9067d498fa29b74bc15cd486/main.py#L178) which takes the detected face and saves it into a folder. You could also ask the user to input the name. What you then need to do is to update `self.embeddings` in `id_data`.

You're very welcome to do this and create a pull request. Otherwise I'll keep it in mind and implement it once I have time.

**Comment by Iamsiraj** [comment]
The main problem i am encountering is to update self.embeddings.
my process is this:
1. when unknow face detected, i pass the face_patches to a function x:
my fucntion x looks like this:
x(self, facepatches):
   
   self.embeddings = self.sess.run(self.embeddings, feed_dict=facepatches)

but it throws an error. how do I update my feed_dict?

**Comment by habrman** [comment]
The embeddings for the crops where already calculated which means that you don't need to do it again. However, if you want to you can look at how it's done [here](https://github.com/habrman/FaceRecognition/blob/4c9516b538161e4eda5bf013ac64430051fc0956/main.py#L155). After that you need to append the embeddings to `self.embeddings` and append new ids to `self.id_names`.

I just updated the code to do this. Just press "s" and it will ask you for an id and save the crop to the proper folder.
